stages:
  - install
  - test
  - deploy

# Define the cache to speed up builds by caching Composer dependencies
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - vendor/
    - node_modules/

# Install dependencies stage
install-dependencies:
  stage: install
  script:
    - echo "Installing PHP dependencies"
    - composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts
  artifacts:
    paths:
      - vendor/
  only:
    - dev  # or remove this to run for all branches

# Run tests stage
test:
  stage: test
  script:
    - echo "Running Laravel tests"
    - php artisan config:cache  # Optimize configuration loading
    - php artisan migrate --env=testing --force  # Run database migrations for testing
  only:
    - dev  # or run on specific branch

# Deploy stage (Optional, add your custom deploy commands)
deploy:
  stage: deploy
  script:
    - echo "Deploying to server"
    - ssh user@server "cd /path/to/your/project && git pull origin dev && composer install --no-dev && php artisan migrate --force && php artisan optimize:clear"
  only:
    - dev  # Run deploy only on dev branch
