[PHP]

memory_limit = 512M

max_execution_time = 60
max_input_time = 60
max_input_vars = 3000

upload_max_filesize = 64M
post_max_size = 64M

date.timezone = UTC


[opcache]

opcache.enable = 1
opcache.enable_cli = 1

opcache.memory_consumption = 256
opcache.interned_strings_buffer = 16
opcache.max_accelerated_files = 20000

opcache.revalidate_freq = 2
